services:
  reverseProxy:
    image: nginx:latest
    container_name: reverseProxyTP
    ports: 
      - 8080:80   # Expose le port 80 du conteneur sur le port 8080 de la machine hôte
    volumes:
      - ./reverseProxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app     # Démarre après le conteneur app
    networks:
      - frontend


  app:
    image: wordpress:latest
    container_name: WordPressApp
    networks:
      - frontend
      - backend     # Communique avec la base de données
    volumes:
      - wp_data:/var/www/html   # Persiste les données de WordPress
    depends_on:
      - db

    env_file: 
      - .env    # Charge les variables d'environnement depuis le fichier .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

  db:
    image: mysql:latest
    container_name: db_mysql
  
    volumes:
      - db_data:/var/lib/mysql  # Persiste les données de la base de données
    restart: always     # Redémarre automatiquement le conteneur en cas de plantage
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    networks:
      - backend   # Communique avec l'application WordPress

  maintenance:
    container_name: maintenance
    build: ./maintenance
    volumes:
      - wp_data:/backup/wordpress   # Monte les volumes de données de WordPress pour les sauvegarder
      - db_data:/backup/db          # Monte les volumes de données pour les sauvegarder
      - ./archive:/archives         # Monte le dossier local archive pour stocker les sauvegardes
      - ~/.ssh:/root/.ssh:ro        # Monte le dossier .ssh en lecture seule pour permettre les connexions SSH
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - app
      - db


volumes:
  db_data:    # Volume pour les données de la base de données
  wp_data:   # Volume pour les données de WordPress 
networks:     # Réseaux pour isoler les services
  frontend:
  backend: